// <auto-generated />
using System;
using HanaMedia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HanaMedia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HanaMedia.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualCost")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("actual_cost");

                    b.Property<decimal>("BookingPrice")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("booking_price");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_name");

                    b.Property<string>("ContractFileUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contract_file_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_description");

                    b.Property<int?>("KolId")
                        .HasColumnType("int")
                        .HasColumnName("kol_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PostLink")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("post_link");

                    b.Property<DateOnly?>("PostingDate")
                        .HasColumnType("date")
                        .HasColumnName("posting_date");

                    b.Property<int?>("PrimaryManagerId")
                        .HasColumnType("int")
                        .HasColumnName("primary_manager_id");

                    b.Property<string>("QuotationFileUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("quotation_file_url");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("dang_cho")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__bookings__3213E83F446D00CB");

                    b.HasIndex("KolId");

                    b.HasIndex("PrimaryManagerId");

                    b.HasIndex(new[] { "Status" }, "idx_bookings_status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.BookingWage", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("AllocatedWage")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("allocated_wage");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("BookingId", "EmployeeId")
                        .HasName("PK__booking___C1B1450B40E1706B");

                    b.HasIndex("EmployeeId");

                    b.ToTable("booking_wages", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.BookingWageAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LogDetail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("log_detail");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("performed_by_user_id");

                    b.HasKey("Id")
                        .HasName("PK__booking___3213E83F0CE97CF5");

                    b.HasIndex("BookingId");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("booking_wage_audit_logs", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.BusinessConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ConfigKey")
                        .HasName("PK__business__BDF6033CB924E59B");

                    b.ToTable("business_configs", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<decimal?>("Allowance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("allowance");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("basic_salary");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("contract_type");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("department");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<DateOnly>("JoinedDate")
                        .HasColumnType("date")
                        .HasColumnName("joined_date");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("position");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("thu_viec")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__employee__3213E83FCE719B40");

                    b.HasIndex("ManagerId");

                    b.HasIndex(new[] { "Email" }, "UQ__employee__AB6E616482BC8677")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "UQ__employee__B9BE370E68AE089C")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.HasIndex(new[] { "Department" }, "idx_employees_dept");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("category");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_name");

                    b.Property<string>("Concept")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concept");

                    b.Property<string>("ContentDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_details");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatorEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("creator_employee_id");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("FeedbackComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback_comment");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("industry");

                    b.Property<string>("Insight")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("insight");

                    b.Property<string>("MoodboardDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moodboard_desc");

                    b.Property<int?>("PrimaryStaffId")
                        .HasColumnType("int")
                        .HasColumnName("primary_staff_id");

                    b.Property<string>("ReferenceLink")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reference_link");

                    b.Property<int?>("ReviewerEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("reviewer_employee_id");

                    b.Property<string>("ScriptText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("script_text");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("y_tuong")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__ideas__3213E83F62C66024");

                    b.HasIndex("CreatorEmployeeId");

                    b.HasIndex("PrimaryStaffId");

                    b.HasIndex("ReviewerEmployeeId");

                    b.HasIndex(new[] { "Status" }, "idx_ideas_status");

                    b.ToTable("ideas", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.Kol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BookingPrice")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("booking_price");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contact_info");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("EngagementRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("engagement_rate");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("int")
                        .HasColumnName("followers_count");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Niche")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("niche");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("platform");

                    b.Property<string>("ProfileLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_link");

                    b.Property<byte?>("RatingScore")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating_score");

                    b.Property<int?>("ResponsibleStaffId")
                        .HasColumnType("int")
                        .HasColumnName("responsible_staff_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("tiem_nang")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__kols__3213E83F79266D0D");

                    b.HasIndex("ResponsibleStaffId");

                    b.HasIndex(new[] { "Platform" }, "idx_kols_platform");

                    b.HasIndex(new[] { "Status" }, "idx_kols_status");

                    b.ToTable("kols", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.SystemAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action_type");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_info");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("LogDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("log_detail");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("module");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__system_a__3213E83F2A038E81");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_audit_logs_created");

                    b.ToTable("system_audit_logs", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.SystemConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ConfigKey")
                        .HasName("PK__system_c__BDF6033C8CA1087D");

                    b.ToTable("system_configs", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F462D2B60");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164982D099A")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__users__F3DBC57222B3371D")
                        .IsUnique();

                    b.HasIndex(new[] { "Role" }, "idx_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HanaMedia.Models.Booking", b =>
                {
                    b.HasOne("HanaMedia.Models.Kol", "Kol")
                        .WithMany("Bookings")
                        .HasForeignKey("KolId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__bookings__kol_id__7E37BEF6");

                    b.HasOne("HanaMedia.Models.Employee", "PrimaryManager")
                        .WithMany("Bookings")
                        .HasForeignKey("PrimaryManagerId")
                        .HasConstraintName("FK__bookings__primar__7F2BE32F");

                    b.Navigation("Kol");

                    b.Navigation("PrimaryManager");
                });

            modelBuilder.Entity("HanaMedia.Models.BookingWage", b =>
                {
                    b.HasOne("HanaMedia.Models.Booking", "Booking")
                        .WithMany("BookingWages")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__booking_w__booki__03F0984C");

                    b.HasOne("HanaMedia.Models.Employee", "Employee")
                        .WithMany("BookingWages")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__booking_w__emplo__04E4BC85");

                    b.Navigation("Booking");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HanaMedia.Models.BookingWageAuditLog", b =>
                {
                    b.HasOne("HanaMedia.Models.Booking", "Booking")
                        .WithMany("BookingWageAuditLogs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__booking_w__booki__08B54D69");

                    b.HasOne("HanaMedia.Models.User", "PerformedByUser")
                        .WithMany("BookingWageAuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__booking_w__perfo__09A971A2");

                    b.Navigation("Booking");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("HanaMedia.Models.Employee", b =>
                {
                    b.HasOne("HanaMedia.Models.Employee", "Manager")
                        .WithMany("InverseManager")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK__employees__manag__6EF57B66");

                    b.HasOne("HanaMedia.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("HanaMedia.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__employees__user___6E01572D");

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HanaMedia.Models.Idea", b =>
                {
                    b.HasOne("HanaMedia.Models.Employee", "CreatorEmployee")
                        .WithMany("IdeaCreatorEmployees")
                        .HasForeignKey("CreatorEmployeeId")
                        .HasConstraintName("FK__ideas__creator_e__114A936A");

                    b.HasOne("HanaMedia.Models.Employee", "PrimaryStaff")
                        .WithMany("IdeaPrimaryStaffs")
                        .HasForeignKey("PrimaryStaffId")
                        .HasConstraintName("FK__ideas__primary_s__123EB7A3");

                    b.HasOne("HanaMedia.Models.Employee", "ReviewerEmployee")
                        .WithMany("IdeaReviewerEmployees")
                        .HasForeignKey("ReviewerEmployeeId")
                        .HasConstraintName("FK__ideas__reviewer___1332DBDC");

                    b.Navigation("CreatorEmployee");

                    b.Navigation("PrimaryStaff");

                    b.Navigation("ReviewerEmployee");
                });

            modelBuilder.Entity("HanaMedia.Models.Kol", b =>
                {
                    b.HasOne("HanaMedia.Models.Employee", "ResponsibleStaff")
                        .WithMany("Kols")
                        .HasForeignKey("ResponsibleStaffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__kols__responsibl__778AC167");

                    b.Navigation("ResponsibleStaff");
                });

            modelBuilder.Entity("HanaMedia.Models.SystemAuditLog", b =>
                {
                    b.HasOne("HanaMedia.Models.User", "User")
                        .WithMany("SystemAuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__system_au__user___17F790F9");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HanaMedia.Models.Booking", b =>
                {
                    b.Navigation("BookingWageAuditLogs");

                    b.Navigation("BookingWages");
                });

            modelBuilder.Entity("HanaMedia.Models.Employee", b =>
                {
                    b.Navigation("BookingWages");

                    b.Navigation("Bookings");

                    b.Navigation("IdeaCreatorEmployees");

                    b.Navigation("IdeaPrimaryStaffs");

                    b.Navigation("IdeaReviewerEmployees");

                    b.Navigation("InverseManager");

                    b.Navigation("Kols");
                });

            modelBuilder.Entity("HanaMedia.Models.Kol", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HanaMedia.Models.User", b =>
                {
                    b.Navigation("BookingWageAuditLogs");

                    b.Navigation("Employee");

                    b.Navigation("SystemAuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
